export const locations = [
    { name: "Mumbai, 2025", id: "mumbai" },
    { name: "Hyderabad, 2025", id: "hyderabad" },
    { name: "Ahmedabad, 2024", id: "ahmedabad" },
    { name: "Pune, 2024", id: "pune" },
    { name: "Bangalore, 2024", id: "bangalore" },
  ];
  
export const images = {
      hyderabad: [
      "/assests/img/PHOTOS-HYDERABAD/0E0A2741.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2742.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2743.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2744.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2745.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2789.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2790.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2791.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2792.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2795.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2796.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2797.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2798.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2799.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2800.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2805.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2806.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2810.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2812.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2816.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2817.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2820.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2821.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2824.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2825.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2828.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2829.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2840.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2841.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2842.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2845.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2846.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2847.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2848.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2849.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2853.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2854.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2855.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2856.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2860.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2861.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2862.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2867.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2869.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2870.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2873.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2874.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2875.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2877.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2878.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2879.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2880.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2883.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2884.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2885.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2886.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2890.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2891.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2892.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2893.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2895.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2896.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2900.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2910.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2911.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2912.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2914.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2916.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2917.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2920.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2921.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2922.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2926.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2927.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2932.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2933.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2934.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2938.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2939.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2940.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2941.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2948.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2949.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2950.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2951.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2952.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2953.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2981.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2982.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2984.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2985.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2986.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2992.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A2993.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3018.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3019.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3020.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3021.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3022.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3025.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3026.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3027.JPG",
      "/assests/img/PHOTOS-HYDERABAD/0E0A3028.JPG"
    ],
    ahmedabad: [
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7878.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7901.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-visitor.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-visitors 2.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7857.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7859.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7862.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7866.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7868.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7870.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7841.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7843.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7846.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7849.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7852.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7854.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7856.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7822.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7823.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7827.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7831.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7834.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7837.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7804.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7806.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7809.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7811.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7812.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7815.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7816.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7820.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7785.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7787.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7790.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7795.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7797.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7800.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7801.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7736.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7739.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7740.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7776.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7779.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7781.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7717.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7719.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7722.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7725.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7727.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7731.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7732.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7735.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-2.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-3.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-4.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-5.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-6.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-7.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-8.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-9.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-16.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-17.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-18.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-19.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-20.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-21.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-22.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-23.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-1.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-10.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-11.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-12.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-13.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-14.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-15.jpg ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7872.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7874.JPG ",
      "/assests/img/gallery-amd-photos/PharmmaEx-Ahmedabad-event-IMG_7876.JPG",
    ],
    pune: [
      "/assests/img/galPuneEvents/DSC08009.JPG",
      "/assests/img/galPuneEvents/DSC08011.JPG",
      "/assests/img/galPuneEvents/DSC08013.JPG",
      "/assests/img/galPuneEvents/DSC08015.JPG",
      "/assests/img/galPuneEvents/DSC08016.JPG",
      "/assests/img/galPuneEvents/DSC08017.JPG",
      "/assests/img/galPuneEvents/DSC08019.JPG",
      "/assests/img/galPuneEvents/DSC08021.JPG",
      "/assests/img/galPuneEvents/DSC08022.JPG",
      "/assests/img/galPuneEvents/DSC08024.JPG",
      "/assests/img/galPuneEvents/DSC08025.JPG",
      "/assests/img/galPuneEvents/DSC08026.JPG",
      "/assests/img/galPuneEvents/DSC08028.JPG",
      "/assests/img/galPuneEvents/DSC08030.JPG",
      "/assests/img/galPuneEvents/DSC08032.JPG",
      "/assests/img/galPuneEvents/DSC08034.JPG",
      "/assests/img/galPuneEvents/DSC08035.JPG",
      "/assests/img/galPuneEvents/DSC08038.JPG",
      "/assests/img/galPuneEvents/DSC08039.JPG",
      "/assests/img/galPuneEvents/DSC08040.JPG",
      "/assests/img/galPuneEvents/DSC08041.JPG",
      "/assests/img/galPuneEvents/DSC08043.JPG",
      "/assests/img/galPuneEvents/DSC08044.JPG",
      "/assests/img/galPuneEvents/DSC08046.JPG",
      "/assests/img/galPuneEvents/DSC08047.JPG",
      "/assests/img/galPuneEvents/DSC08049.JPG",
      "/assests/img/galPuneEvents/DSC08052.JPG",
      "/assests/img/galPuneEvents/DSC08054.JPG",
      "/assests/img/galPuneEvents/DSC08056.JPG",
      "/assests/img/galPuneEvents/DSC08057.JPG",
      "/assests/img/galPuneEvents/DSC08058.JPG",
      "/assests/img/galPuneEvents/DSC08061.JPG",
      "/assests/img/galPuneEvents/DSC08064.JPG",
      "/assests/img/galPuneEvents/DSC08066.JPG",
      "/assests/img/galPuneEvents/DSC08069.JPG",
      "/assests/img/galPuneEvents/DSC08073.JPG",
      "/assests/img/galPuneEvents/DSC08074.JPG",
      "/assests/img/galPuneEvents/DSC08077.JPG",
      "/assests/img/galPuneEvents/DSC08079.JPG",
      "/assests/img/galPuneEvents/DSC08081.JPG",
      "/assests/img/galPuneEvents/DSC08082.JPG",
      "/assests/img/galPuneEvents/DSC08084.JPG",
      "/assests/img/galPuneEvents/DSC08085.JPG",
      "/assests/img/galPuneEvents/DSC08086.JPG",
      "/assests/img/galPuneEvents/DSC08087.JPG",
      "/assests/img/galPuneEvents/DSC08088.JPG",
      "/assests/img/galPuneEvents/DSC08089.JPG",
      "/assests/img/galPuneEvents/DSC08090.JPG",
      "/assests/img/galPuneEvents/DSC08092.JPG",
      "/assests/img/galPuneEvents/DSC08094.JPG",
      "/assests/img/galPuneEvents/DSC08097.JPG",
      "/assests/img/galPuneEvents/DSC08099.JPG",
      "/assests/img/galPuneEvents/DSC08100.JPG",
      "/assests/img/galPuneEvents/DSC08102.JPG",
      "/assests/img/galPuneEvents/DSC08105.JPG",
      "/assests/img/galPuneEvents/DSC08107.JPG",
      "/assests/img/galPuneEvents/DSC08108.JPG",
      "/assests/img/galPuneEvents/DSC08110.JPG",
      "/assests/img/galPuneEvents/DSC08111.JPG",
      "/assests/img/galPuneEvents/DSC08113.JPG",
      "/assests/img/galPuneEvents/DSC08116.JPG",
      "/assests/img/galPuneEvents/DSC08118.JPG",
      "/assests/img/galPuneEvents/DSC08120.JPG",
      "/assests/img/galPuneEvents/DSC08123.JPG",
      "/assests/img/galPuneEvents/DSC08124.JPG",
      "/assests/img/galPuneEvents/DSC08129.JPG",
      "/assests/img/galPuneEvents/DSC08131.JPG",
      "/assests/img/galPuneEvents/DSC08132.JPG",
      "/assests/img/galPuneEvents/DSC08133.JPG",
      "/assests/img/galPuneEvents/DSC07975.JPG",
      "/assests/img/galPuneEvents/DSC07984.JPG",
      "/assests/img/galPuneEvents/DSC07987.JPG",
      "/assests/img/galPuneEvents/DSC07988.JPG",
      "/assests/img/galPuneEvents/DSC07991.JPG",
      "/assests/img/galPuneEvents/DSC07992.JPG",
      "/assests/img/galPuneEvents/DSC07997.JPG",
      "/assests/img/galPuneEvents/DSC07999.JPG",
      "/assests/img/galPuneEvents/DSC08000.JPG",
      "/assests/img/galPuneEvents/DSC08003.JPG",
      "/assests/img/galPuneEvents/DSC08006.JPG"
    ],
    bangalore: [
      "/assests/img/gal2024/IMG-001.jpg",
      "/assests/img/gal2024/IMG-002.jpg",
      "/assests/img/gal2024/IMG-003.jpg",
      "/assests/img/gal2024/IMG-004.jpg",
      "/assests/img/gal2024/IMG-005.jpg",
      "/assests/img/gal2024/IMG-007.jpg",
      "/assests/img/gal2024/IMG-008.jpg",
      "/assests/img/gal2024/IMG-009.jpg",
      "/assests/img/gal2024/IMG-0010.jpg",
      "/assests/img/gal2024/IMG-0011.jpg",
      "/assests/img/gal2024/IMG-0012.jpg",
      "/assests/img/gal2024/IMG-0013.jpg",
      "/assests/img/gal2024/IMG-0014.jpg",
      "/assests/img/gal2024/IMG-0015.jpg",
      "/assests/img/gal2024/IMG-0016.jpg",
      "/assests/img/gal2024/IMG-0017.jpg",
      "/assests/img/gal2024/IMG-0018.jpg",
      "/assests/img/gal2024/IMG-0019.jpg",
      "/assests/img/gal2024/IMG-0020.jpg",
      "/assests/img/gal2024/IMG-0021.jpg",
      "/assests/img/gal2024/IMG-0022.jpg",
      "/assests/img/gal2024/IMG-0023.jpg",
      "/assests/img/gal2024/IMG-0024.jpg",
      "/assests/img/gal2024/IMG-0025.jpg",
      "/assests/img/gal2024/IMG-0026.jpg",
      "/assests/img/gal2024/IMG-0027.jpg",
      "/assests/img/gal2024/IMG-0028.jpg",
      "/assests/img/gal2024/IMG-0029.jpg",
      "/assests/img/gal2024/IMG-0030.jpg",
      "/assests/img/gal2024/IMG-0031.jpg",
      "/assests/img/gal2024/IMG-0032.jpg",
      "/assests/img/gal2024/IMG-0033.jpg",
      "/assests/img/gal2024/IMG-0034.jpg",
      "/assests/img/gal2024/IMG-0035.jpg",
      "/assests/img/gal2024/IMG-0036.jpg",
      "/assests/img/gal2024/IMG-0037.jpg",
      "/assests/img/gal2024/IMG-0038.jpg",
      "/assests/img/gal2024/IMG-0039.jpg",
      "/assests/img/gal2024/IMG-0040.jpg",
      "/assests/img/gal2024/IMG-0041.jpg",
      "/assests/img/gal2024/IMG-0042.jpg",
      "/assests/img/gal2024/IMG-0043.jpg",
      "/assests/img/gal2024/IMG-0044.jpg",
      "/assests/img/gal2024/IMG-0045.jpg",
      "/assests/img/gal2024/IMG-0046.jpg",
      "/assests/img/gal2024/IMG-0047.jpg",
      "/assests/img/gal2024/IMG-0048.jpg",
      "/assests/img/gal2024/IMG-0049.jpg",
      "/assests/img/gal2024/IMG-0050.jpg",
      "/assests/img/gal2024/IMG-0051.jpg",
      "/assests/img/gal2024/IMG-0052.jpg",
      "/assests/img/gal2024/IMG-0053.jpg",
      "/assests/img/gal2024/IMG-0054.jpg",
      "/assests/img/gal2024/IMG-0055.jpg",
      "/assests/img/gal2024/IMG-0056.jpg",
      "/assests/img/gal2024/IMG-0057.jpg",
      "/assests/img/gal2024/IMG-0058.jpg",
      "/assests/img/gal2024/IMG-0059.jpg",
      "/assests/img/gal2024/IMG-0060.jpg",
      "/assests/img/gal2024/IMG-0061.jpg",
      "/assests/img/gal2024/IMG-0062.jpg",
      "/assests/img/gal2024/IMG-0063.jpg",
      "/assests/img/gal2024/IMG-0064.jpg",
      "/assests/img/gal2024/IMG-0065.jpg",
      "/assests/img/gal2024/IMG-0066.jpg",
      "/assests/img/gal2024/IMG-0067.jpg",
      "/assests/img/gal2024/IMG-0068.jpg",
      "/assests/img/gal2024/IMG-0069.jpg",
      "/assests/img/gal2024/IMG-0070.jpg",
      "/assests/img/gal2024/IMG-0071.jpg",
      "/assests/img/gal2024/IMG-0072.jpg",
      "/assests/img/gal2024/IMG-0073.jpg",
      "/assests/img/gal2024/IMG-0074.jpg",
      "/assests/img/gal2024/IMG-0075.jpg",
      "/assests/img/gal2024/IMG-0076.jpg",
      "/assests/img/gal2024/IMG-0077.jpg",
      "/assests/img/gal2024/IMG-0078.jpg",
      "/assests/img/gal2024/IMG-0079.jpg",
      "/assests/img/gal2024/IMG-0080.jpg",
      "/assests/img/gal2024/IMG-0081.jpg",
      "/assests/img/gal2024/IMG-0082.jpg",
      "/assests/img/gal2024/IMG-0083.jpg",
      "/assests/img/gal2024/IMG-0084.jpg",
      "/assests/img/gal2024/IMG-0085.jpg",
      "/assests/img/gal2024/IMG-0086.jpg",
      "/assests/img/gal2024/IMG-0087.jpg",
      "/assests/img/gal2024/IMG-0088.jpg",
      "/assests/img/gal2024/IMG-0089.jpg",
      "/assests/img/gal2024/IMG-0090.jpg",
    ],
    mumbai:[
      "/assests/img/photos-mumbai/ABCD0111.JPG",
      "/assests/img/photos-mumbai/ABCD9673.JPG",
      "/assests/img/photos-mumbai/ABCD9675.JPG",
      "/assests/img/photos-mumbai/ABCD9678.JPG",
      "/assests/img/photos-mumbai/ABCD9680.JPG",
      "/assests/img/photos-mumbai/ABCD9681.JPG",
      "/assests/img/photos-mumbai/ABCD9689.JPG",
      "/assests/img/photos-mumbai/ABCD9698.JPG",
      "/assests/img/photos-mumbai/ABCD9700.JPG",
      "/assests/img/photos-mumbai/ABCD9712.JPG",
      "/assests/img/photos-mumbai/ABCD9715.JPG",
      "/assests/img/photos-mumbai/ABCD9730.JPG",
      "/assests/img/photos-mumbai/ABCD9738.JPG",
      "/assests/img/photos-mumbai/ABCD9740.JPG",
      "/assests/img/photos-mumbai/ABCD9742.JPG",
      "/assests/img/photos-mumbai/ABCD9744.JPG",
      "/assests/img/photos-mumbai/ABCD9771.JPG",
      "/assests/img/photos-mumbai/ABCD9775.JPG",
      "/assests/img/photos-mumbai/ABCD9776.JPG",
      "/assests/img/photos-mumbai/ABCD9778.JPG",
      "/assests/img/photos-mumbai/ABCD9780.JPG",
      "/assests/img/photos-mumbai/ABCD9781.JPG",
      "/assests/img/photos-mumbai/ABCD9783.JPG",
      "/assests/img/photos-mumbai/ABCD9786.JPG",
      "/assests/img/photos-mumbai/ABCD9787.JPG",
      "/assests/img/photos-mumbai/ABCD9790.JPG",
      "/assests/img/photos-mumbai/ABCD9793.JPG",
      "/assests/img/photos-mumbai/ABCD9796.JPG",
      "/assests/img/photos-mumbai/ABCD9803.JPG",
      "/assests/img/photos-mumbai/ABCD9805.JPG",
      "/assests/img/photos-mumbai/ABCD9808.JPG",
      "/assests/img/photos-mumbai/ABCD9820.JPG",
      "/assests/img/photos-mumbai/ABCD9837.JPG",
      "/assests/img/photos-mumbai/ABCD9842.JPG",
      "/assests/img/photos-mumbai/ABCD9843.JPG",
      "/assests/img/photos-mumbai/ABCD9849.JPG",
      "/assests/img/photos-mumbai/ABCD9857.JPG",
      "/assests/img/photos-mumbai/ABCD9886.JPG",
      "/assests/img/photos-mumbai/ABCD9908.JPG",
      "/assests/img/photos-mumbai/ABCD9936.JPG",
    ]
  };