import Head from "next/head";
import Image from "next/image";

import Header from "@/src/components/header/header";

import Footer from "@/src/components/bannerHome/Footer";
import InnerPageBanner from "@/src/components/bannerHome/InnerPageBanner";
import AboutMain from "@/src/components/bannerHome/AboutMain";
import MissionBox from "@/src/components/bannerHome/MissionBox";
import WhoWeServe from "@/src/components/bannerHome/WhoWeServe";
import PastExhibitions from "@/src/components/bannerHome/PastExhibitions";
import TeamSection from "@/src/components/bannerHome/TeamSection";
import ExhibitionGallery from "@/src/components/bannerHome/ExhibitionGallery";

 

 

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      <InnerPageBanner pageName="Who we are" bgImage="/assests/img/aboutBanner.svg" />
      <AboutMain />
      <MissionBox/>
      <WhoWeServe />
      <PastExhibitions />
      <TeamSection /> 
      <ExhibitionGallery/>
      <Footer />

     
     
    
     
    </>
  )
}
