import Head from "next/head";
import Image from "next/image";

import Header from "@/src/components/header/header";

import Footer from "@/src/components/bannerHome/Footer";
import InnerPageBanner from "@/src/components/bannerHome/InnerPageBanner";
import ClientTestimonials from "@/src/components/bannerHome/ClientTestimonials";
 
 

 

export default function ClientReview
() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      <InnerPageBanner pageName="Reviews" bgImage="/assests/img/reviewBanner.svg" />
      <ClientTestimonials />
   
      <Footer />

     
     
    
     
    </>
  )
}
