import Head from "next/head";
import Image from "next/image";

import Header from "@/src/components/header/header";

import Footer from "@/src/components/bannerHome/Footer";
import InnerPageBanner from "@/src/components/bannerHome/InnerPageBanner";
import ContactUs from "@/src/components/bannerHome/ContactUs";
import ExhibitionQueries from "@/src/components/bannerHome/ExhibitionQueries";
import Ticker from "@/src/components/bannerHome/Ticker";

 

 

export default function About() {
  return (
    <>
      <Head>
        <title>Contact-us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src='https://www.google.com/recaptcha/api.js'></script>
      </Head>
      <Header />      
      <InnerPageBanner pageName="Contact-Us" bgImage="/assests/img/aboutBanner.svg" />

      <ContactUs />
      <ExhibitionQueries />
      <Ticker />
      <Footer />
    </>
  )
}
