import Head from "next/head";
import Image from "next/image";

import Header from "@/src/components/header/header";

import Footer from "@/src/components/bannerHome/Footer";
import InnerPageBanner from "@/src/components/bannerHome/InnerPageBanner";
import ExhibitionGallery from "@/src/components/bannerHome/ExhibitionGallery";
import ExhibitorRegistrationPage from "@/src/components/bannerHome/ExhibitorRegistrationPage";

const Exhibitor = () => {
    return (
      <>
       <Head>
       
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      <InnerPageBanner pageName="Exhibitor Registration Form" bgImage="/assests/img/exbg.svg" />
      <ExhibitorRegistrationPage />
      <ExhibitionGallery/>
      <Footer />
      </>
    );
};

export default Exhibitor;