import Footer from "@/pharmex/src/components/bannerHome/Footer";
import Header from "@/pharmex/src/components/header/header";
import Head from "next/head";
import React, { useEffect, useState } from "react";

export default function Order() {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  // Fetch orders from API
  useEffect(() => {
    const fetchOrders = async () => {
      try {
        const res = await fetch("https://apis.pharmmaex.com/orders"); // your API
        const data = await res.json();
        setOrders(data?.orders);
      } catch (err) {
        console.error("Error fetching orders:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchOrders();
  }, []);

  // Update payment status in backend
  const handleStatusChange = async (orderId, newStatus) => {
    try {
      const res = await fetch(`https://apis.pharmmaex.com/change-status`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ status: newStatus, orderId: orderId }),
      });

      if (res.ok) {
        setOrders((prev) =>
          prev.map((order) =>
            order.orderId == orderId ? { ...order, status: newStatus } : order
          )
        );
        alert("Updated Successfully!");
      } else {
        alert("❌ Failed to update status");
      }
    } catch (err) {
      console.error("Error updating status:", err);
    }
  };

  //   if (loading) return <p className="p-4">Loading orders...</p>;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container mt-5 mb-5">
        <h2 className="text-center fw-bold mb-4">Orders</h2>
        {loading ? (
          <div
            className="d-flex justify-content-center align-items-center"
            style={{ height: "300px" }}
          >
            <div className="spinner-border text-black" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
          </div>
        ) : (
          <div className="table-responsive">
            <table className="table table-bordered table-striped table-hover w-100">
              <thead className="table-dark">
                <tr>
                  <th>Order ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Amount</th>
                  <th>Cart</th>
                  <th>Created At</th>
                  <th>Payment verification</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((order) => (
                  <tr key={order._id}>
                    <td>{order.orderId}</td>
                    <td>{order.name}</td>
                    <td>{order.email}</td>
                    <td>{order.phone}</td>
                    <td>
                      {order.amount} {order.currency}
                    </td>
                    <td>
                      {order.cart &&
                        Object.entries(order.cart).map(([item, qty]) => (
                          <div key={item}>
                            {item}: {qty}
                          </div>
                        ))}
                    </td>
                    <td>{new Date(order.createdAt).toLocaleString()}</td>
                    <td>
                      <select
                        value={order.status}
                        onChange={(e) =>
                          handleStatusChange(order.orderId, e.target.value)
                        }
                        className="form-select form-select-sm"
                      >
                        <option value="pending">Pending</option>
                        <option value="verified">Verified</option>
                      </select>
                    </td>
                  </tr>
                ))}
                {orders.length === 0 && (
                  <tr>
                    <td className="text-center" colSpan="8">
                      No orders found
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
      <Footer />
    </>
  );
}
