import Head from "next/head";
import Header from "@/src/components/header/header";
import Footer from "@/src/components/bannerHome/Footer";
import InnerPageBanner from "@/src/components/bannerHome/InnerPageBanner";
import styles from "@/styles/PrivacyPolicy.module.css";

const PrivacyPolicy = () => {
  return (
    <>
      <Head>
        <title>PharmaEx</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <InnerPageBanner pageName="Privacy Policy" bgImage="/assests/img/privacy.png" />
      <div className={styles.container}>
        <div className="innerContainer mx-auto">
          <h1 className={styles.pageTitle}>Privacy Policy</h1>

          <section className={styles.section}>
            <h2>Introduction</h2>
            <p>At PharmmaEx, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your personal information when you visit our website or interact with our services.</p>
            <p>By using our website, you agree to the terms of this Privacy Policy.</p>
          </section>

          <section className={styles.section}>
            <h2>Information We Collect</h2>
            <p>We may collect the following types of information:</p>
            <ul>
              <li><b>Personal Information:</b> Name, email address, phone number, company name, and other contact details provided via forms (e.g., contact, registration, or downloads).</li>
              <li><b>Event Information:</b> Details you submit during exhibitor registration, visitor registration, or inquiry about sponsorships or booths.</li>
              <li><b>Automatically Collected Data:</b> Device information, browser type, IP address, pages visited, and browsing behavior using cookies and analytics tools (e.g., Google Analytics).</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>How We Use Your Information</h2>
            <p>We may use your data for the following purposes:</p>
            <ul>
              <li>To respond to your inquiries or requests</li>
              <li>To process registrations and send confirmations</li>
              <li>To send updates about the exhibition or future events</li>
              <li>To improve our website and user experience</li>
              <li>To send marketing communications, newsletters, or promotional materials (you can opt out anytime)</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>Cookies and Similar Technologies</h2>
            <p>We use cookies, web beacons, and tracking pixels to:</p>
            <ul>
              <li>Facilitate website functionality</li>
              <li>Analyze site usage and performance</li>
              <li>Customize user experience</li>
              <li>Support marketing and advertising efforts</li>
            </ul>
            <p>You can manage or disable cookies in your browser, although this may affect site functionality.</p>
          </section>

          <section className={styles.section}>
            <h2>Disclosure of Your Information</h2>
            <p>We do not sell or rent personal data to third parties. We may share your information in these scenarios:</p>
            <ul>
              <li><b>Service Providers & Event Partners:</b> We may share with vendors who support our event (e.g., registration platforms, email services), strictly for defined purposes and under confidentiality.</li>
              <li><b>Legal & Safety Compliance:</b> We may disclose to comply with legal obligations (e.g., court orders), enforce site policy, or protect the rights and safety of users and third parties.</li>
              <li><b>Merger or Acquisition:</b> If our business is involved in a merger, sale, or asset acquisition, your information may be transferred as part of the transaction under legally binding terms.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>Third-Party Links</h2>
            <p>Our site may link to external websites (e.g., payment processors, exhibitor partner sites). We are not responsible for their content or data practices. Please review each site's privacy policy before submitting personal information.</p>
          </section>

          <section className={styles.section}>
            <h2>Data Security & Retention</h2>
            <p>We implement robust security measures, such as:</p>
            <ul>
              <li>SSL encryption for data in transit</li>
              <li>Secure hosting environments and firewalls</li>
              <li>Access controls and regular data audits</li>
            </ul>
            <p>Although we employ industry-standard protections, no digital system is infallible. You acknowledge that you provide information at your own risk.</p>
            <p><b>Data Retention:</b><br/>We retain personal data only as long as necessary to fulfill the purposes outlined (e.g., 2 years post-event), or as mandated by law.</p>
          </section>

          <section className={styles.section}>
            <h2>International Data Transfers</h2>
            <p>Your data may be stored and processed in servers located in India or abroad. If we transfer your information internationally, we will ensure it is protected under legally recognized data security frameworks.</p>
          </section>

          <section className={styles.section}>
            <h2>Policy Updates</h2>
            <p>This Privacy Policy may be updated from time to time (e.g., changes in technology, legal requirements). We'll post updates here with the latest Effective Date. We recommend returning periodically to review any changes.</p>
          </section>

          <section className={styles.section}>
            <h2>Contact Us</h2>
            <p>For questions, requests, or concerns regarding this Policy or our data practices, please contact:<br/>
              PharmmaEx Privacy Team<br/>
              📧 Email: [Insert Privacy/Support Email]<br/>
              📞 Phone: [Insert Contact Number]<br/>
              🌐 Website: <a href="https://pharmmaex.com/" target="_blank" rel="noopener noreferrer">https://pharmmaex.com/</a>
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PrivacyPolicy;
